### PR TITLE
Slovenian translation for Power8 1.6.3 Build 1636

### PR DESCRIPTION
**Pull request by JadranR**
[Slovenian translation_Power8_1.6.3.sl.zip](https://github.com/AgentMC/power8/files/9387794/Slovenian.translation_Power8_1.6.3.sl.zip)
Hi,

I send you now Slovenian translation for Power8 1.6.3 Build 1636.
Please, send Me link for download Test version before release New version.
With respect,
Jadran Rudec

### CODE REVIEW

**Comment by AgentMC** [comment]
Hello Jardan!
Here's the debug version for testing the localization. The culture is locked as "sl" and the version is lowered.
[Power8-debug-sl.zip](https://github.com/AgentMC/power8/files/9387905/Power8-debug-sl.zip)

**Warning**: if you want to make any further changes, please use this file as a basis https://github.com/AgentMC/power8/blob/Rel_1_6_4/Properties/Resources.sl.resx because I corrected one line break you lost.

**Comment by AgentMC** [comment]
It's out now. Thanks again!

**Comment by JadranR** [comment]
Hi Mike,
Thank you for release Power8 Release 1.6.4
<https://github.com/AgentMC/power8/releases/tag/v.1.6.4.1640>
Best Regards,
Jadran

V V ned., 21. avg. 2022 ob 14:06 je oseba Mike Makarov <
***@***.***> napisala:

**Comment by JadranR** [comment]
Hi Mike,

Pleas, see Pull request on GitHub. Slovenian translation is Done.

Please, see attached screenshot  too.

Best regards,
Jadran Rudec

V V sob., 20. avg. 2022 ob 21:22 je oseba Mike Makarov <
***@***.***> napisala:

**Comment by AgentMC** [comment]
Hey Jadran, not sure I get you. The Slovenian translation you provided is integrated into Power8 and is out as v.1.6.4 on Aug 21.

I do not see any other open PRs.

Is there anything I am missing?

**Comment by JadranR** [comment]
Hi Mike ,
Thank you for info.

Best Regards,
Jadran

V V sre., 12. okt. 2022 ob 15:18 je oseba Mike Makarov <
***@***.***> napisala:

**Pull request closed without merging**
